import { getSiteLocale, type SiteLocale } from "@/lib/i18n"

/**
 * Chrome and component labels that are not content. Page copy lives in the
 * page components next to the markup it belongs to; this table exists for the
 * shared widgets, where threading a translation through every caller would be
 * worse than looking one up.
 */
const UI_STRINGS = {
  en: {
    backToTop: "Back to top",
    commentBody: "Comment",
    commentEmpty: "No comments yet. Be the first.",
    commentFailed: "Could not post the comment. Please try again.",
    commentLoadFailed: "Comments could not be loaded.",
    commentName: "Name (optional)",
    commentNamePlaceholder: "Anonymous",
    commentPending: "Thanks — your comment is waiting to be reviewed.",
    commentPlaceholder: "Write a comment…",
    commentRateLimited:
      "Too many comments in a short time. Please wait a little.",
    commentSubmit: "Post comment",
    commentSubmitting: "Posting…",
    comments: "Comments",
    breadcrumbNav: "Breadcrumb navigation",
    closeImage: "Close the image",
    copyPostUrl: "Copy post URL",
    copyUrl: "Copy URL",
    featuredProject: "Featured project: ",
    firstProject: "You're at the first project!",
    goHome: "Go to home page",
    home: "Home",
    lastProject: "You're at the last project!",
    menu: "Menu",
    morePages: "More pages",
    next: "Next",
    nextPage: "Go to next page",
    navigateHome: "Navigate to home page",
    newestPost: "You're at the newest post!",
    nextPost: "Next Post",
    overview: "Overview",
    nextProject: "Next Project",
    oldestPost: "You're at the oldest post!",
    pagination: "Pagination",
    postActions: "Post actions",
    postLabel: (title: string) => `Post: ${title}`,
    previous: "Previous",
    previousPage: "Go to previous page",
    previousPost: "Previous Post",
    previousProject: "Previous Project",
    published: "Published",
    readingProgress: "Reading progress",
    relatedPosts: "Related posts",
    reactionInsight: "Insightful",
    reactionLike: "Like",
    reactionCount: "{label}: {count}",
    reactions: "Reactions",
    readingTime: (minutes: number) => `${minutes} min read`,
    search: "Search",
    searchEmpty: "Nothing matched that.",
    searching: "Searching…",
    searchPlaceholder: "Search posts and projects",
    searchResultCount: "{count} results",
    searchUnavailable: "Search is unavailable on this build.",
    siteNav: "Site navigation",
    tableOfContents: "Table of contents",
    theme: "Theme",
    themeAuto: "Auto",
    themeDark: "Dark",
    themeLight: "Light",
    toggleMenu: "Toggle menu",
    updated: "Updated",
  },
  ja: {
    backToTop: "ページ上部へ戻る",
    commentBody: "コメント",
    commentEmpty: "まだコメントはありません。最初の1件をどうぞ。",
    commentFailed:
      "コメントを送信できませんでした。時間をおいて再度お試しください。",
    commentLoadFailed: "コメントを読み込めませんでした。",
    commentName: "お名前（任意）",
    commentNamePlaceholder: "匿名",
    commentPending: "ありがとうございます。確認後に公開されます。",
    commentPlaceholder: "コメントを入力…",
    commentRateLimited: "短時間に投稿しすぎです。少し時間をおいてください。",
    commentSubmit: "コメントする",
    commentSubmitting: "送信中…",
    comments: "コメント",
    breadcrumbNav: "パンくずリスト",
    closeImage: "画像を閉じる",
    copyPostUrl: "記事のURLをコピー",
    copyUrl: "URLをコピー",
    featuredProject: "注目のプロジェクト: ",
    firstProject: "これが最初のプロジェクトです",
    goHome: "ホームへ戻る",
    home: "ホーム",
    lastProject: "これが最後のプロジェクトです",
    menu: "メニュー",
    morePages: "その他のページ",
    next: "次へ",
    nextPage: "次のページへ",
    navigateHome: "ホームへ移動",
    newestPost: "これが最新の記事です",
    nextPost: "次の記事",
    overview: "冒頭",
    nextProject: "次のプロジェクト",
    oldestPost: "これが最初の記事です",
    pagination: "ページ送り",
    postActions: "記事の操作",
    postLabel: (title: string) => `記事: ${title}`,
    previous: "前へ",
    previousPage: "前のページへ",
    previousPost: "前の記事",
    previousProject: "前のプロジェクト",
    published: "公開日",
    readingProgress: "読み進めた割合",
    relatedPosts: "関連記事",
    reactionInsight: "なるほど",
    reactionLike: "いいね",
    reactionCount: "{label}: {count}件",
    reactions: "リアクション",
    readingTime: (minutes: number) => `約${minutes}分で読めます`,
    search: "検索",
    searchEmpty: "一致するものがありませんでした。",
    searching: "検索中…",
    searchPlaceholder: "記事とプロジェクトを検索",
    searchResultCount: "{count}件見つかりました",
    searchUnavailable: "このビルドでは検索を利用できません。",
    siteNav: "サイトナビゲーション",
    tableOfContents: "目次",
    theme: "テーマ",
    themeAuto: "自動",
    themeDark: "ダーク",
    themeLight: "ライト",
    toggleMenu: "メニューを開閉",
    updated: "更新日",
  },
} as const satisfies Record<SiteLocale, Record<string, unknown>>

export type UIStrings = (typeof UI_STRINGS)[SiteLocale]

/** Accepts a locale, or the pathname to derive one from. */
export const getUIStrings = (localeOrPath: string): UIStrings =>
  UI_STRINGS[
    localeOrPath === "en" || localeOrPath === "ja"
      ? localeOrPath
      : getSiteLocale(localeOrPath)
  ]
