import { getSiteLocale, type SiteLocale } from "@/lib/i18n"

/**
 * Chrome and component labels that are not content. Page copy lives in the
 * page components next to the markup it belongs to; this table exists for the
 * shared widgets, where threading a translation through every caller would be
 * worse than looking one up.
 */
const UI_STRINGS = {
  en: {
    backToTop: "Back to top",
    stageLabels: {
      seedling: "seedling",
      budding: "budding",
      evergreen: "evergreen",
    },
    email: "Email",
    viewProjects: "View projects",
    seeAll: "See all →",
    toggleTheme: "Change theme",
    sourceCode: "Source code",
    sourceContent: "Source content",
    colorPalette: "Color palette",
    projectLinks: {
      code: "Code",
      doc: "Documentation",
      paper: "Paper",
      release: "Release",
      url: "Website",
    },
    previousSubpost: "Previous subpost",
    nextSubpost: "Next subpost",
    noOlderSubpost: "No older subpost",
    noNewerSubpost: "No newer subpost",
    noParentPost: "No parent post",
    commentBody: "Comment",
    commentEmpty: "No comments yet. Be the first.",
    commentFailed: "Could not post the comment. Please try again.",
    commentLoadFailed: "Comments could not be loaded.",
    commentName: "Name (optional)",
    commentNamePlaceholder: "Anonymous",
    commentPending: "Thanks — your comment is waiting to be reviewed.",
    commentPrivacy: "How comments are handled",
    commentPlaceholder: "Write a comment…",
    commentRateLimited:
      "Too many comments in a short time. Please wait a little.",
    commentSubmit: "Post comment",
    commentSubmitting: "Posting…",
    comments: "Comments",
    currentPost: "Current post",
    currentSubpost: "Current subpost",
    breadcrumbNav: "Breadcrumb navigation",
    closeImage: "Close the image",
    openImage: "Open image",
    imageViewer: "Image viewer",
    zoomImage: "Zoom in",
    fitImage: "Fit to screen",
    originalImage: "Open original",
    imageArea: "Image (scroll to explore when zoomed)",
    imageLoadFailed: "The image could not be loaded. Try opening the original.",
    copyEmail: "Copy email address",
    copyPostUrl: "Copy post URL",
    copyUrl: "Copy URL",
    copied: "Copied!",
    copyFailed: "Could not copy. Please try again.",
    featuredProject: "Featured project: ",
    firstProject: "You're at the first project!",
    goHome: "Go to home page",
    home: "Home",
    lastProject: "You're at the last project!",
    menu: "Menu",
    morePages: "More pages",
    next: "Next",
    nextPage: "Go to next page",
    navigateHome: "Navigate to home page",
    sendEmail: (address: string) => `Send email to ${address}`,
    skipToContent: "Skip to main content",
    newestPost: "You're at the newest post!",
    nextPost: "Next Post",
    overview: "Overview",
    nextProject: "Next Project",
    oldestPost: "You're at the oldest post!",
    pagination: "Pagination",
    postActions: "Post actions",
    postAndSubposts: "Post and subposts",
    postNavigation: "Post navigation",
    postLabel: (title: string) => `Post: ${title}`,
    previous: "Previous",
    previousPage: "Go to previous page",
    previousPost: "Previous Post",
    previousProject: "Previous Project",
    published: "Published",
    readingProgress: "Reading progress",
    relatedPosts: "Related posts",
    reactionInsight: "Insightful",
    reactionLike: "Like",
    reactionCount: "{label}: {count}",
    reactionLoadFailed: "Could not load reactions. Try reloading the page.",
    reactionFailed: "Could not send your reaction. Please try again.",
    reactions: "Reactions",
    readingTime: (minutes: number) => `${minutes} min read`,
    pronunciationGuide: "How to pronounce my name",
    playPronunciation: (name: string) => `Play the pronunciation of ${name}`,
    search: "Search",
    searchEmpty: "Nothing matched that.",
    searching: "Searching…",
    searchPlaceholder: "Search posts and projects",
    searchResultCount: "{count} results",
    searchUnavailable: "Search is unavailable on this build.",
    siteNav: "Site navigation",
    subpost: "Subpost",
    subpostCount: (count: number) =>
      `${count} ${count === 1 ? "subpost" : "subposts"}`,
    subposts: "Subposts",
    subpostsNavigation: "Subposts navigation",
    subpostsSection: "Subposts section",
    parentPost: "Parent post",
    tableOfContents: "Table of contents",
    theme: "Theme",
    themeAuto: "Auto",
    themeDark: "Dark",
    themeLight: "Light",
    toggleMenu: "Toggle menu",
    updated: "Updated",
  },
  ja: {
    backToTop: "ページ上部へ戻る",
    stageLabels: {
      seedling: "アイデア・メモ",
      budding: "推敲中",
      evergreen: "まとめ",
    },
    email: "メール",
    viewProjects: "プロジェクトを見る",
    seeAll: "すべて見る →",
    toggleTheme: "テーマを切り替える",
    sourceCode: "ソースコード",
    sourceContent: "コンテンツのソース",
    colorPalette: "配色",
    projectLinks: {
      code: "ソースコード",
      doc: "ドキュメント",
      paper: "論文",
      release: "リリース",
      url: "サイト",
    },
    previousSubpost: "前の補足記事",
    nextSubpost: "次の補足記事",
    noOlderSubpost: "これが最初の補足記事です",
    noNewerSubpost: "これが最後の補足記事です",
    noParentPost: "親記事がありません",
    commentBody: "コメント",
    commentEmpty: "まだコメントはありません。最初の1件をどうぞ。",
    commentFailed:
      "コメントを送信できませんでした。時間をおいて再度お試しください。",
    commentLoadFailed: "コメントを読み込めませんでした。",
    commentName: "お名前（任意）",
    commentNamePlaceholder: "匿名",
    commentPending: "ありがとうございます。確認後に公開されます。",
    commentPrivacy: "コメントの取り扱いについて",
    commentPlaceholder: "コメントを入力…",
    commentRateLimited: "短時間に投稿しすぎです。少し時間をおいてください。",
    commentSubmit: "コメントする",
    commentSubmitting: "送信中…",
    comments: "コメント",
    currentPost: "現在の記事",
    currentSubpost: "現在の補足記事",
    breadcrumbNav: "パンくずリスト",
    closeImage: "画像を閉じる",
    openImage: "画像を開く",
    imageViewer: "画像ビューア",
    zoomImage: "拡大する",
    fitImage: "全体を表示",
    originalImage: "原寸画像を開く",
    imageArea: "画像（拡大時はスクロールできます）",
    imageLoadFailed:
      "画像を読み込めませんでした。原寸画像を開いてお試しください。",
    copyEmail: "メールアドレスをコピー",
    copyPostUrl: "記事のURLをコピー",
    copyUrl: "URLをコピー",
    copied: "コピーしました",
    copyFailed: "コピーできませんでした。もう一度お試しください。",
    featuredProject: "注目のプロジェクト: ",
    firstProject: "これが最初のプロジェクトです",
    goHome: "ホームへ戻る",
    home: "ホーム",
    lastProject: "これが最後のプロジェクトです",
    menu: "メニュー",
    morePages: "その他のページ",
    next: "次へ",
    nextPage: "次のページへ",
    navigateHome: "ホームへ移動",
    sendEmail: (address: string) => `${address}へメールを送る`,
    skipToContent: "本文へ移動",
    newestPost: "これが最新の記事です",
    nextPost: "次の記事",
    overview: "冒頭",
    nextProject: "次のプロジェクト",
    oldestPost: "これが最初の記事です",
    pagination: "ページ送り",
    postActions: "記事の操作",
    postAndSubposts: "記事と補足記事",
    postNavigation: "記事内ナビゲーション",
    postLabel: (title: string) => `記事: ${title}`,
    previous: "前へ",
    previousPage: "前のページへ",
    previousPost: "前の記事",
    previousProject: "前のプロジェクト",
    published: "公開日",
    readingProgress: "読み進めた割合",
    relatedPosts: "関連記事",
    reactionInsight: "なるほど",
    reactionLike: "いいね",
    reactionCount: "{label}: {count}件",
    reactionLoadFailed:
      "リアクションを読み込めませんでした。ページを再読み込みしてください。",
    reactionFailed:
      "リアクションを送信できませんでした。もう一度お試しください。",
    reactions: "リアクション",
    readingTime: (minutes: number) => `約${minutes}分で読めます`,
    pronunciationGuide: "名前の読み方",
    playPronunciation: (name: string) => `${name}の読み方を再生`,
    search: "検索",
    searchEmpty: "一致するものがありませんでした。",
    searching: "検索中…",
    searchPlaceholder: "記事とプロジェクトを検索",
    searchResultCount: "{count}件見つかりました",
    searchUnavailable: "このビルドでは検索を利用できません。",
    siteNav: "サイトナビゲーション",
    subpost: "補足記事",
    subpostCount: (count: number) => `補足記事${count}件`,
    subposts: "補足記事",
    subpostsNavigation: "補足記事のナビゲーション",
    subpostsSection: "補足記事のセクション",
    parentPost: "親記事",
    tableOfContents: "目次",
    theme: "テーマ",
    themeAuto: "自動",
    themeDark: "ダーク",
    themeLight: "ライト",
    toggleMenu: "メニューを開閉",
    updated: "更新日",
  },
} as const satisfies Record<SiteLocale, Record<string, unknown>>

export type UIStrings = (typeof UI_STRINGS)[SiteLocale]

/** Accepts a locale, or the pathname to derive one from. */
export const getUIStrings = (localeOrPath: string): UIStrings =>
  UI_STRINGS[
    localeOrPath === "en" || localeOrPath === "ja"
      ? localeOrPath
      : getSiteLocale(localeOrPath)
  ]
