[keitaro]
id          = "keitaro"
name        = "Keitaro Ueki"
bio         = "AI engineer and undergraduate student at Waseda University"
affiliation = "Waseda University"

[keitaro.links]
github = "https://github.com/97kuek"
